BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[idx_ano_mes_ativo] (
    [ANO_MES] DECIMAL(18,0) NOT NULL,
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [DIA] DECIMAL(18,0),
    [DOLAR] DECIMAL(18,4) CONSTRAINT [DF_idx_ano_mes_ativo_DOLAR] DEFAULT 0,
    CONSTRAINT [PK_idx_ano_mes_ativo] PRIMARY KEY CLUSTERED ([ANO_MES])
);

-- CreateTable
CREATE TABLE [dbo].[idx_cnpj_ativo] (
    [CNPJ] DECIMAL(18,0) NOT NULL,
    [CNPJ_FORMATADO] VARCHAR(50) NOT NULL,
    [CNPJ_RAIZ] VARCHAR(50),
    [CNPJ_VALIDO] BIT NOT NULL,
    CONSTRAINT [PK_idx_cnpj_ativo] PRIMARY KEY CLUSTERED ([CNPJ])
);

-- CreateTable
CREATE TABLE [dbo].[idx_cnpj_ativo_demanda] (
    [CNPJ_ESTABELECIMENTO] DECIMAL(18,0) NOT NULL,
    [CNPJ_FORMATADO] VARCHAR(50) NOT NULL,
    [CNPJ_RAIZ] VARCHAR(50),
    [CNPJ_VALIDO] BIT NOT NULL,
    [EMAIL_REPRESENTANTE_DEMANDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_idx_cnpj_demanda_ativo_EMAIL_REPRESENTANTE_DEMANDA] DEFAULT 'orfao@orfao',
    [SETORIZACAO_DEMANDA] VARCHAR(100) NOT NULL,
    [EMAIL_REPRESENTANTE_VENDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_idx_cnpj_demanda_ativo_EMAIL_REPRESENTANTE_VENDA] DEFAULT 'orfao@orfao',
    [SETORIZACAO_VENDA] VARCHAR(100) NOT NULL,
    [EMAIL_REPRESENTANTE_ACESSO] VARCHAR(100) NOT NULL CONSTRAINT [DF_idx_cnpj_demanda_ativo_EMAIL_REPRESENTANTE_ACESSO] DEFAULT 'orfao@orfao',
    [SETORIZACAO_ACESSO] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_idx_cnpj_ativo_demanda] PRIMARY KEY CLUSTERED ([CNPJ_ESTABELECIMENTO])
);

-- CreateTable
CREATE TABLE [dbo].[idx_cnpj_ativo_distribuidor] (
    [CNPJ_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL,
    [ID_GRUPO_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL,
    CONSTRAINT [PK_idx_cnpj_distribuidor_ativo] PRIMARY KEY CLUSTERED ([CNPJ_DISTRIBUIDOR])
);

-- CreateTable
CREATE TABLE [dbo].[idx_cnpj_ativo_setorizado] (
    [CNPJ] DECIMAL(18,0) NOT NULL,
    [CNPJ_FORMATADO] VARCHAR(50) NOT NULL,
    [CNPJ_RAIZ] VARCHAR(50),
    [CNPJ_VALIDO] BIT NOT NULL,
    [EMAIL_REPRESENTANTE_DEMANDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_idx_cnpj_ativo_setorizado_EMAIL_REPRESENTANTE_DEMANDA] DEFAULT 'orfao@orfao',
    [SETORIZACAO_DEMANDA] VARCHAR(100) NOT NULL,
    [EMAIL_REPRESENTANTE_VENDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_idx_cnpj_ativo_setorizado_EMAIL_REPRESENTANTE_VENDA] DEFAULT 'orfao@orfao',
    [SETORIZACAO_VENDA] VARCHAR(100) NOT NULL,
    [EMAIL_REPRESENTANTE_ACESSO] VARCHAR(100) NOT NULL CONSTRAINT [DF_idx_cnpj_ativo_setorizado_EMAIL_REPRESENTANTE_ACESSO] DEFAULT 'orfao@orfao',
    [SETORIZACAO_ACESSO] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_idx_cnpj_ativo_setorizado] PRIMARY KEY CLUSTERED ([CNPJ])
);

-- CreateTable
CREATE TABLE [dbo].[idx_cod_municipio_ativo] (
    [COD_MUNICIPIO] VARCHAR(7) NOT NULL,
    CONSTRAINT [PK_idx_cod_municipio_ativo] PRIMARY KEY CLUSTERED ([COD_MUNICIPIO])
);

-- CreateTable
CREATE TABLE [dbo].[idx_cod_produto_ativo] (
    [COD_PRODUTO] VARCHAR(50) NOT NULL,
    [COD_PRODUTO_LINHA] DECIMAL(18,0) NOT NULL,
    CONSTRAINT [PK_idx_cod_produtos] PRIMARY KEY CLUSTERED ([COD_PRODUTO])
);

-- CreateTable
CREATE TABLE [dbo].[idx_cod_produto_linha_ativo] (
    [COD_PRODUTO_LINHA] DECIMAL(18,0) NOT NULL,
    CONSTRAINT [PK_idx_cod_produto_linha] PRIMARY KEY CLUSTERED ([COD_PRODUTO_LINHA])
);

-- CreateTable
CREATE TABLE [dbo].[idx_email_representante_ativo] (
    [EMAIL_REPRESENTANTE] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_idx_email_representante_ativo] PRIMARY KEY CLUSTERED ([EMAIL_REPRESENTANTE])
);

-- CreateTable
CREATE TABLE [dbo].[idx_id_grupo_distribuidor_ativo] (
    [ID_GRUPO_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL,
    CONSTRAINT [PK_idx_id_grupo_distribuidor_ativo] PRIMARY KEY CLUSTERED ([ID_GRUPO_DISTRIBUIDOR])
);

-- CreateTable
CREATE TABLE [dbo].[idx_setorizacao] (
    [CNPJ] DECIMAL(18,0) NOT NULL,
    [EMAIL_REPRESENTANTE_DEMANDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_idx_setorizacao_ativa_EMAIL_REPRESENTANTE_DEMANDA] DEFAULT 'orfao@orfao',
    [SETORIZACAO_DEMANDA] VARCHAR(100) NOT NULL,
    [EMAIL_REPRESENTANTE_VENDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_idx_setorizacao_ativa_EMAIL_REPRESENTANTE_VENDA] DEFAULT 'orfao@orfao',
    [SETORIZACAO_VENDA] VARCHAR(100) NOT NULL,
    [EMAIL_REPRESENTANTE_ACESSO] VARCHAR(100) NOT NULL CONSTRAINT [DF_Table_1_EMAIL_REPRESENTANTE_VENDA1] DEFAULT 'orfao@orfao',
    [SETORIZACAO_ACESSO] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_idx_setorizacao] PRIMARY KEY CLUSTERED ([CNPJ])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_atualizacao] (
    [Atualizacao] DATETIME NOT NULL,
    CONSTRAINT [PK_pbi_d_atualizacao] PRIMARY KEY CLUSTERED ([Atualizacao])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_datas_anos] (
    [(pk_idx_Ano)] DECIMAL(18,0) NOT NULL,
    [Ano] VARCHAR(10) NOT NULL,
    [#idx_Periodo] DECIMAL(18,0) NOT NULL,
    [Periodo] VARCHAR(20) NOT NULL,
    CONSTRAINT [PK_pbi_d_datas_anos] PRIMARY KEY CLUSTERED ([(pk_idx_Ano)]),
    CONSTRAINT [IX_pbi_d_datas_anos] UNIQUE NONCLUSTERED ([Ano])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_datas_meses] (
    [(pk_Ano_Mes_Universal)] DECIMAL(18,0) NOT NULL,
    [#idx_Ano] DECIMAL(18,0) NOT NULL,
    [Ano] VARCHAR(10) NOT NULL,
    [#idx_Mes] DECIMAL(18,0) NOT NULL,
    [Mes] VARCHAR(10) NOT NULL,
    [#idx_Trimestre] DECIMAL(18,0) NOT NULL,
    [Trimestre] VARCHAR(10) NOT NULL,
    [#idx_Semestre] DECIMAL(18,0) NOT NULL,
    [Semestre] VARCHAR(10) NOT NULL,
    [#idx_Periodo] DECIMAL(18,0) NOT NULL,
    [Periodo] VARCHAR(20) NOT NULL,
    [@Mes-Atual] BIT NOT NULL,
    [#idx_MesYTD] DECIMAL(18,0),
    [@YTD] BIT NOT NULL,
    [@YTD_Atual] BIT NOT NULL,
    [@YTD_Passado] BIT NOT NULL,
    [@YTD_Retrasado] BIT NOT NULL,
    [#idx_Mes36] DECIMAL(18,0) NOT NULL,
    [Mes 36] VARCHAR(30),
    [@MAT_36] BIT NOT NULL,
    [@MAT_24] BIT NOT NULL,
    [@MAT_12] BIT NOT NULL,
    [@MAT_06] BIT NOT NULL,
    [@MAT_03] BIT NOT NULL,
    [@MAT_Atual] BIT NOT NULL,
    [@MAT_Passado] BIT NOT NULL,
    [@MAT_Retrasado] BIT NOT NULL,
    CONSTRAINT [PK_pbi_d_datas_meses] PRIMARY KEY CLUSTERED ([(pk_Ano_Mes_Universal)])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_distribuidor_grupo] (
    [(pk_Id_Grupo_Distribuidor)] DECIMAL(18,0) NOT NULL,
    [Grupo] VARCHAR(100) NOT NULL,
    [Tipo] VARCHAR(100) NOT NULL,
    [#fk_Email_Representante] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_pbi_d_distribuidor_grupo] PRIMARY KEY CLUSTERED ([(pk_Id_Grupo_Distribuidor)])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_estabelecimento] (
    [(pk_CNPJ_Estabelecimento)] DECIMAL(18,0) NOT NULL,
    [CNPJ Raiz] VARCHAR(50),
    [CNPJ] VARCHAR(50) NOT NULL,
    [CNES] VARCHAR(7) NOT NULL,
    [Tipo] VARCHAR(12) NOT NULL,
    [Estabelecimento] VARCHAR(556),
    [Nome Fantasia] VARCHAR(300),
    [Razao Social] VARCHAR(300),
    [Grupo] VARCHAR(100) NOT NULL,
    [Logradouro] VARCHAR(500),
    [Numero] VARCHAR(50),
    [Complemento] VARCHAR(300),
    [Bairro] VARCHAR(300),
    [CEP] VARCHAR(8),
    [#fk_Cod_Municipio] VARCHAR(7) NOT NULL,
    [Cidade] VARCHAR(200),
    [UF] VARCHAR(2) NOT NULL,
    [@Capital] BIT NOT NULL,
    [Micro Regiao] VARCHAR(100) NOT NULL,
    [Meso Regiao] VARCHAR(100) NOT NULL,
    [Regiao] VARCHAR(100) NOT NULL,
    [Pais] VARCHAR(100) NOT NULL,
    [Natureza] NVARCHAR(200) NOT NULL,
    [Esfera] VARCHAR(50) NOT NULL,
    [Gestao] VARCHAR(50) NOT NULL,
    [Tipo Pessoa] VARCHAR(50) NOT NULL,
    [@Target Demanda] BIT NOT NULL,
    [Setorizacão Demanda] VARCHAR(100) NOT NULL,
    [#fk_Email_Representante_Demanda] VARCHAR(100) NOT NULL,
    [Representante Demanda] VARCHAR(50) NOT NULL,
    [Gerente Demanda] VARCHAR(50) NOT NULL,
    [Diretor Demanda] VARCHAR(50) NOT NULL,
    [@Target Venda] BIT NOT NULL,
    [Setorizacão Venda] VARCHAR(100) NOT NULL,
    [#fk_Email_Representante_Venda] VARCHAR(100) NOT NULL,
    [Representante Venda] VARCHAR(50) NOT NULL,
    [Gerente Venda] VARCHAR(50) NOT NULL,
    [Diretor Venda] VARCHAR(50) NOT NULL,
    [Setorizacão Acesso] VARCHAR(100) NOT NULL,
    [#fk_Email_Representante_Acesso] VARCHAR(100) NOT NULL,
    [Representante Acesso] VARCHAR(50) NOT NULL,
    [Gerente Acesso] VARCHAR(50) NOT NULL,
    [Diretor Acesso] VARCHAR(50) NOT NULL,
    CONSTRAINT [PK_pbi_d_estabelecimentos] PRIMARY KEY CLUSTERED ([(pk_CNPJ_Estabelecimento)])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_fv_representante] (
    [(pk_Email_Representante)] VARCHAR(100) NOT NULL,
    [Representante] VARCHAR(50) NOT NULL,
    [Gerente] VARCHAR(50) NOT NULL,
    [Diretor] VARCHAR(50) NOT NULL,
    [@Ativo] BIT NOT NULL,
    CONSTRAINT [PK_pbi_d_fv_representante] PRIMARY KEY CLUSTERED ([(pk_Email_Representante)])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_movimento_tipo] (
    [(pk_Cod_Tipo_Movimento)] VARCHAR(8) NOT NULL,
    [Tipo] VARCHAR(200),
    [Cod_Grupo] VARCHAR(2),
    [Grupo] VARCHAR(50),
    [Cod_Forma] VARCHAR(2),
    [Forma] VARCHAR(50),
    [Cod_Valor] VARCHAR(2),
    [Valor] VARCHAR(50),
    [Cod_Agrupamento] VARCHAR(2),
    [Agrupamento] VARCHAR(50),
    CONSTRAINT [PK_pbi_d_movimento_tipo] PRIMARY KEY CLUSTERED ([(pk_Cod_Tipo_Movimento)])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_produto] (
    [(pk_Cod_Produto)] VARCHAR(50) NOT NULL,
    [Produto] VARCHAR(100) NOT NULL,
    [#fk_Cod_Linha] DECIMAL(18,0) NOT NULL,
    [Linha] VARCHAR(100) NOT NULL,
    [#idx_Grupo] DECIMAL(18,0) NOT NULL,
    [Grupo] VARCHAR(100) NOT NULL,
    [#idx_Grupo_Venda] DECIMAL(18,0) NOT NULL,
    [Grupo Venda] VARCHAR(100) NOT NULL,
    [Unidade Venda] VARCHAR(100) NOT NULL,
    [ASP BRL] DECIMAL(18,2) NOT NULL,
    [ASP USD] DECIMAL(18,2) NOT NULL,
    [EQ Fator] DECIMAL(18,4) NOT NULL,
    [Unidade Equivalente] VARCHAR(100) NOT NULL,
    [@Ativo] BIT NOT NULL,
    [#fk_Cod_Produto_Agrupado] VARCHAR(20),
    CONSTRAINT [PK_pbi_produtos] PRIMARY KEY CLUSTERED ([(pk_Cod_Produto)])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_produto_agrupado] (
    [(pk_Cod_Produto_Agrupado)] VARCHAR(20) NOT NULL,
    [Produto_Agrupado] VARCHAR(100) NOT NULL,
    [Linha_Agrupado] VARCHAR(100) NOT NULL,
    [#fk_Cod_Linha] DECIMAL(18,0) NOT NULL,
    [Linha] VARCHAR(100) NOT NULL,
    [#idx_Grupo] DECIMAL(18,0) NOT NULL,
    [Grupo] VARCHAR(100) NOT NULL,
    [#idx_Grupo_Venda] DECIMAL(18,0) NOT NULL,
    [Grupo Venda] VARCHAR(100) NOT NULL,
    [#fk_Cod_Produto] VARCHAR(50),
    [Produto] VARCHAR(100),
    [ASP BRL] DECIMAL(18,2),
    [ASP USD] DECIMAL(18,2),
    [EQ Fator] DECIMAL(18,4),
    [Unidade Venda] VARCHAR(100),
    [Unidade Equivalente] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_pbi_d_produto_agrupamento] PRIMARY KEY CLUSTERED ([(pk_Cod_Produto_Agrupado)])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_d_produto_linha] (
    [(pk_Cod_Linha)] DECIMAL(18,0) NOT NULL,
    [Linha] VARCHAR(100) NOT NULL,
    [#idx_Grupo] DECIMAL(18,0) NOT NULL,
    [Grupo] VARCHAR(100) NOT NULL,
    [#idx_Grupo_Venda] DECIMAL(18,0) NOT NULL,
    [Grupo Venda] VARCHAR(100) NOT NULL,
    [Unidade Equivalente] VARCHAR(100) NOT NULL,
    [#fk_Cod_Produto_Agrupado] VARCHAR(20) NOT NULL,
    CONSTRAINT [PK_pbi_d_produto_linha] PRIMARY KEY CLUSTERED ([(pk_Cod_Linha)]),
    CONSTRAINT [IX_pbi_d_produto_linha] UNIQUE NONCLUSTERED ([#fk_Cod_Produto_Agrupado])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_f_estoque_ultimo] (
    [[#fk_Ano_Mes] DECIMAL(18,0) NOT NULL,
    [#fk_Id_Grupo_Distribuidor] DECIMAL(18,0) NOT NULL,
    [Data] DATE,
    CONSTRAINT [PK_pbi_f_estoque_ultimo] PRIMARY KEY CLUSTERED ([[#fk_Ano_Mes],[#fk_Id_Grupo_Distribuidor])
);

-- CreateTable
CREATE TABLE [dbo].[pbi_f_movimento] (
    [#fk_Cod_Tipo_Movimento] VARCHAR(8) NOT NULL,
    [Cod_Grupo] VARCHAR(2) NOT NULL,
    [Cod_Forma] VARCHAR(2) NOT NULL,
    [Cod_Valor] VARCHAR(2) NOT NULL,
    [Cod_Agrupamento] VARCHAR(2) NOT NULL,
    [#fk_Ano_Mes] DECIMAL(18,0) NOT NULL,
    [#fk_Email_Representante] VARCHAR(100) NOT NULL,
    [#fk_Id_Grupo_Distribuidor] DECIMAL(18,0) NOT NULL,
    [#fk_CNPJ_Estabelecimento] DECIMAL(18,0) NOT NULL,
    [#fk_Cod_Produto] VARCHAR(50),
    [#fk_Cod_Linha] DECIMAL(18,0) NOT NULL,
    [#fk_Cod_Produto_Agrupado] VARCHAR(20) NOT NULL,
    [=qt] DECIMAL(38,0) NOT NULL CONSTRAINT [DF_pbi_f_movimento_=qt] DEFAULT 0,
    [=qt_UN] DECIMAL(38,0) NOT NULL CONSTRAINT [DF_pbi_f_movimento_=qt_UN] DEFAULT 0,
    [=qt_EQ] DECIMAL(38,4) NOT NULL CONSTRAINT [DF_pbi_f_movimento_=qt_EQ] DEFAULT 0,
    [=qt_BRL_ASP] DECIMAL(38,2) NOT NULL CONSTRAINT [DF_pbi_f_movimento_=qt_BRL_ASP] DEFAULT 0,
    [=qt_USD_ASP] DECIMAL(38,4) NOT NULL CONSTRAINT [DF_pbi_f_movimento_=qt_USD_ASP] DEFAULT 0,
    [=qt_BRL] DECIMAL(38,2) NOT NULL CONSTRAINT [DF_pbi_f_movimento_=qt_BRL] DEFAULT 0
);

-- CreateTable
CREATE TABLE [dbo].[pbi_f_movimento_36] (
    [#fk_Cod_Tipo_Movimento] VARCHAR(8) NOT NULL,
    [#fk_Email_Representante] VARCHAR(100) NOT NULL,
    [#fk_Id_Grupo_Distribuidor] DECIMAL(18,0) NOT NULL,
    [#fk_CNPJ_Estabelecimento] DECIMAL(18,0) NOT NULL,
    [#fk_Cod_Linha] DECIMAL(18,0) NOT NULL,
    [#fk_Cod_Produto] VARCHAR(50),
    [#fk_Cod_Produto_Agrupado] VARCHAR(20) NOT NULL,
    [MAT 03] DECIMAL(38,0),
    [MAT 06] DECIMAL(38,0),
    [MAT 12] DECIMAL(38,0),
    [MAT 24] DECIMAL(38,0),
    [MAT 36] DECIMAL(38,0),
    [MAT Retrasado] DECIMAL(38,0),
    [MAT Passado] DECIMAL(38,0),
    [MAT Atual] DECIMAL(38,0),
    [Media 24] DECIMAL(38,6),
    [Media 12] DECIMAL(38,6),
    [Media 06] DECIMAL(38,6),
    [Media 03] DECIMAL(38,6),
    [Media Ponderada] DECIMAL(38,8)
);

-- CreateTable
CREATE TABLE [dbo].[pbi_f_movimento_mensal] (
    [#fk_Cod_Tipo_Movimento] VARCHAR(8) NOT NULL,
    [#fk_idx_Ano] DECIMAL(18,0) NOT NULL,
    [#fk_Email_Representante] VARCHAR(100) NOT NULL,
    [#fk_Id_Grupo_Distribuidor] DECIMAL(18,0) NOT NULL,
    [#fk_CNPJ_Estabelecimento] DECIMAL(18,0) NOT NULL,
    [#fk_Cod_Linha] DECIMAL(18,0) NOT NULL,
    [#fk_Cod_Produto] VARCHAR(50),
    [#fk_Cod_Produto_Agrupado] VARCHAR(20) NOT NULL,
    [01-Jul] DECIMAL(38,0),
    [02-Ago] DECIMAL(38,0),
    [03-Set] DECIMAL(38,0),
    [04-Out] DECIMAL(38,0),
    [05-Nov] DECIMAL(38,0),
    [06-Dez] DECIMAL(38,0),
    [07-Jan] DECIMAL(38,0),
    [08-Fev] DECIMAL(38,0),
    [09-Mar] DECIMAL(38,0),
    [10-Abr] DECIMAL(38,0),
    [11-Mai] DECIMAL(38,0),
    [12-Jun] DECIMAL(38,0),
    [Tri-01] DECIMAL(38,0),
    [Tri-02] DECIMAL(38,0),
    [Tri-03] DECIMAL(38,0),
    [Tri-04] DECIMAL(38,0),
    [Semestre-01] DECIMAL(38,0),
    [Semestre-02] DECIMAL(38,0),
    [YTD] DECIMAL(38,0),
    [FY] DECIMAL(38,0),
    [Media] DECIMAL(38,6),
    [Mes-Atual] DECIMAL(38,0)
);

-- CreateTable
CREATE TABLE [dbo].[pbi_f_movimento_tmp] (
    [#fk_Cod_Tipo_Movimento] VARCHAR(8) NOT NULL,
    [Cod_Grupo] VARCHAR(2) NOT NULL,
    [Cod_Forma] VARCHAR(2) NOT NULL,
    [Cod_Valor] VARCHAR(2) NOT NULL,
    [Cod_Agrupamento] VARCHAR(2) NOT NULL,
    [#fk_Ano_Mes] DECIMAL(18,0) NOT NULL,
    [#fk_Email_Representante] VARCHAR(100) NOT NULL,
    [#fk_Id_Grupo_Distribuidor] DECIMAL(18,0) NOT NULL,
    [#fk_CNPJ_Estabelecimento] DECIMAL(18,0) NOT NULL,
    [#fk_Cod_Produto] VARCHAR(50),
    [#fk_Cod_Linha] DECIMAL(18,0) NOT NULL,
    [#fk_Cod_Produto_Agrupado] VARCHAR(20) NOT NULL,
    [=qt] DECIMAL(38,0) NOT NULL,
    [=qt_UN] DECIMAL(38,0) NOT NULL,
    [=qt_EQ] DECIMAL(38,4) NOT NULL,
    [=qt_BRL_ASP] DECIMAL(38,2) NOT NULL,
    [=qt_USD_ASP] DECIMAL(38,4) NOT NULL,
    [=qt_BRL] DECIMAL(38,2) NOT NULL
);

-- CreateTable
CREATE TABLE [dbo].[SYS_DOLAR_PADRAO] (
    [ID] DECIMAL(18,0) NOT NULL,
    [DOLAR_PADRAO] DECIMAL(18,4) NOT NULL,
    [OBSERVACAO] VARCHAR(100),
    [DATA_ATUALIZACAO] DATETIME,
    CONSTRAINT [PK_SYS_DOLAR_PADRAO] PRIMARY KEY CLUSTERED ([ID])
);

-- CreateTable
CREATE TABLE [dbo].[SYS_FABRICANTE] (
    [CNPJ_FABRICANTE] DECIMAL(18,0) NOT NULL,
    [ID_GRUPO_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_FABRI__ID_GR__1FF8A574] DEFAULT 1,
    CONSTRAINT [PK__TBL_FABR__3B37865761A75822] PRIMARY KEY CLUSTERED ([CNPJ_FABRICANTE])
);

-- CreateTable
CREATE TABLE [dbo].[SYS_MOVIMENTO_AGRUPAMENTO] (
    [COD_AGRUPAMENTO] VARCHAR(2) NOT NULL,
    [AGRUPAMENTO] VARCHAR(50),
    CONSTRAINT [PK_SYS_MOVIMENTO_AGRUPAMENTO_COD_AGRUPAMENTO] PRIMARY KEY CLUSTERED ([COD_AGRUPAMENTO]),
    CONSTRAINT [IX_SYS_MOVIMENTO_AGRUPAMENTO] UNIQUE NONCLUSTERED ([AGRUPAMENTO])
);

-- CreateTable
CREATE TABLE [dbo].[SYS_MOVIMENTO_FORMA] (
    [COD_FORMA] VARCHAR(2) NOT NULL,
    [FORMA] VARCHAR(50),
    CONSTRAINT [PK_SYS_MOVIMENTO_FORMA] PRIMARY KEY CLUSTERED ([COD_FORMA]),
    CONSTRAINT [IX_SYS_MOVIMENTO_FORMA] UNIQUE NONCLUSTERED ([FORMA])
);

-- CreateTable
CREATE TABLE [dbo].[SYS_MOVIMENTO_GRUPO] (
    [COD_GRUPO] VARCHAR(2) NOT NULL,
    [GRUPO] VARCHAR(50),
    CONSTRAINT [PK_SYS_MOVIMENTO_GRUPO_COD_GRUPO] PRIMARY KEY CLUSTERED ([COD_GRUPO]),
    CONSTRAINT [IX_SYS_MOVIMENTO_GRUPO_COD_GRUPO] UNIQUE NONCLUSTERED ([COD_GRUPO])
);

-- CreateTable
CREATE TABLE [dbo].[SYS_MOVIMENTO_TIPO] (
    [COD_TIPO] VARCHAR(8) NOT NULL,
    [TIPO] VARCHAR(200),
    [COD_GRUPO] VARCHAR(2) NOT NULL,
    [COD_FORMA] VARCHAR(2) NOT NULL,
    [COD_VALOR] VARCHAR(2) NOT NULL,
    [COD_AGRUPAMENTO] VARCHAR(2) NOT NULL,
    CONSTRAINT [PK_SYS_MOVIMENTO_TIPO] PRIMARY KEY CLUSTERED ([COD_TIPO]),
    CONSTRAINT [IX_SYS_MOVIMENTO_TIPO_TIPO] UNIQUE NONCLUSTERED ([TIPO])
);

-- CreateTable
CREATE TABLE [dbo].[SYS_MOVIMENTO_VALOR] (
    [COD_VALOR] VARCHAR(2) NOT NULL,
    [VALOR] VARCHAR(50),
    CONSTRAINT [PK_SYS_MOVIMENTO_VALOR_COD_VALOR] PRIMARY KEY CLUSTERED ([COD_VALOR]),
    CONSTRAINT [IX_SYS_MOVIMENTO_VALOR_VALOR] UNIQUE NONCLUSTERED ([VALOR])
);

-- CreateTable
CREATE TABLE [dbo].[SYS_USUARIOS_PADRAO] (
    [EMAIL] VARCHAR(100) NOT NULL CONSTRAINT [DF_SYS_USUARIOS_PADRAO_EMAIL] DEFAULT '@',
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_SYS_USUARIOS_PADRAO_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_SYS_USUARIOS_PADRAO] PRIMARY KEY CLUSTERED ([EMAIL])
);

-- CreateTable
CREATE TABLE [dbo].[sysdiagrams] (
    [name] NVARCHAR(128) NOT NULL,
    [principal_id] INT NOT NULL,
    [diagram_id] INT NOT NULL IDENTITY(1,1),
    [version] INT,
    [definition] VARBINARY(max),
    CONSTRAINT [PK__sysdiagr__C2B05B6132392507] PRIMARY KEY CLUSTERED ([diagram_id]),
    CONSTRAINT [UK_principal_name] UNIQUE NONCLUSTERED ([principal_id],[name])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_DATAS_ANOS] (
    [ANO] DECIMAL(18,0) NOT NULL,
    CONSTRAINT [PK_TBL_DATAS_ANOS] PRIMARY KEY CLUSTERED ([ANO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_DATAS_DIAS] (
    [DIA] DECIMAL(18,0) NOT NULL,
    CONSTRAINT [PK_TBL_DATAS_DIAS] PRIMARY KEY CLUSTERED ([DIA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_DATAS_DOLAR] (
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [DOLAR] DECIMAL(18,4) NOT NULL CONSTRAINT [DF_TBL_DATAS_DOLAR_DOLAR] DEFAULT 0,
    CONSTRAINT [PK_TBL_DATAS_DOLAR] PRIMARY KEY CLUSTERED ([ANO],[MES])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_DATAS_MESES] (
    [MES] DECIMAL(18,0) NOT NULL,
    [MES_SIGLA] VARCHAR(10) NOT NULL,
    [TRIMESTRE] DECIMAL(18,0) NOT NULL,
    [TRIMESTRE_SIGLA] VARCHAR(10) NOT NULL,
    [SEMESTRE] DECIMAL(18,0) NOT NULL,
    [SEMESTRE_SIGLA] VARCHAR(10) NOT NULL,
    [ANO_FISCAL_FATOR] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_DATAS__ANO_F__7E77B618] DEFAULT 0,
    [MES_FISCAL] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_DATAS__MES_F__7F6BDA51] DEFAULT 0,
    [MES_FISCAL_SIGLA] VARCHAR(10) NOT NULL,
    [TRIMESTRE_FISCAL] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_DATAS__TRIME__015422C3] DEFAULT 0,
    [TRIMESTRE_FISCAL_SIGLA] VARCHAR(10) NOT NULL,
    [SEMESTRE_FISCAL] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_DATAS__SEMES__024846FC] DEFAULT 0,
    [SEMESTRE_FISCAL_SIGLA] VARCHAR(10) NOT NULL,
    CONSTRAINT [PK_TBL_DATAS_MESES] PRIMARY KEY CLUSTERED ([MES])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_DATAS_PERIODOS] (
    [PERIODO_INDICE] DECIMAL(18,0) NOT NULL,
    [PERIODO] VARCHAR(20),
    CONSTRAINT [PK__TBL_DATAS_PERIODOS] PRIMARY KEY CLUSTERED ([PERIODO_INDICE]),
    CONSTRAINT [IX_TBL_DATAS_PERIODOS] UNIQUE NONCLUSTERED ([PERIODO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_DISTRIBUIDORES] (
    [CNPJ_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL,
    [ID_GRUPO_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_DISTR__ID_GR__1209AD79] DEFAULT 1,
    [ESTABELECIMENTO] VARCHAR(300) NOT NULL,
    [RAZAO_SOCIAL] VARCHAR(300) NOT NULL,
    [NOME_FANTASIA] VARCHAR(300) NOT NULL,
    [CIDADE] VARCHAR(200) NOT NULL,
    [UF] VARCHAR(2) NOT NULL,
    [ATIVO] BIT NOT NULL CONSTRAINT [DF__TBL_DISTR__ATIVO__15DA3E5D] DEFAULT 1,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_DISTRIBUIDORES_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_DISTRIBUIDORES_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_DISTRIBUIDORES] PRIMARY KEY CLUSTERED ([CNPJ_DISTRIBUIDOR])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_DISTRIBUIDORES_GRUPOS] (
    [ID_GRUPO_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL,
    [COD_TIPO_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL,
    [GRUPO_DISTRIBUIDOR] VARCHAR(100) NOT NULL,
    [EMAIL_REPRESENTANTE_VENDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_DISTRIBUIDORES_GRUPOS_EMAIL_REPRESENTANTE_VENDA] DEFAULT 'orfao@orfao',
    [EMAIL_REPRESENTANTE_DEMANDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_DISTRIBUIDORES_GRUPOS_EMAIL_REPRESENTANTE_DEMANDA] DEFAULT 'orfao@orfao',
    [ATIVO] BIT NOT NULL CONSTRAINT [DF__TBL_DISTR__ATIVO__4959E263] DEFAULT 1,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_DISTRIBUIDORES_GRUPOS_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_DISTRIBUIDORES_GRUPOS_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_DISTRIBUIDORES_GRUPOS] PRIMARY KEY CLUSTERED ([ID_GRUPO_DISTRIBUIDOR]),
    CONSTRAINT [IX_TBL_DISTRIBUIDORES_GRUPOS] UNIQUE NONCLUSTERED ([GRUPO_DISTRIBUIDOR])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_DISTRIBUIDORES_TIPO] (
    [COD_TIPO_DISTRIBUDOR] DECIMAL(18,0) NOT NULL,
    [TIPO_DISTRIBUIDOR] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_TBL_DISTRIBUIDORES_TIPO] PRIMARY KEY CLUSTERED ([COD_TIPO_DISTRIBUDOR]),
    CONSTRAINT [IX_TBL_DISTRIBUIDORES_TIPO] UNIQUE NONCLUSTERED ([TIPO_DISTRIBUIDOR])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_ESTABELECIMENTOS] (
    [CNPJ] DECIMAL(18,0) NOT NULL,
    [CNES] VARCHAR(7) NOT NULL CONSTRAINT [DF__TBL_ESTABE__CNES__2C538F61] DEFAULT '0000000',
    [RAZAO_SOCIAL] VARCHAR(300) NOT NULL,
    [NOME_FANTASIA] VARCHAR(300) NOT NULL,
    [ID_GRUPO_ESTABELECIMENTO] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_ESTAB__ID_GR__2D47B39A] DEFAULT 1,
    [LOGRADOURO] VARCHAR(500),
    [NUMERO] VARCHAR(50),
    [COMPLEMENTO] VARCHAR(300),
    [BAIRRO] VARCHAR(300),
    [CEP] VARCHAR(8) NOT NULL CONSTRAINT [DF__TBL_ESTABEL__CEP__2E3BD7D3] DEFAULT '0000000',
    [COD_MUNICIPIO] VARCHAR(7) NOT NULL,
    [COD_NATUREZA] DECIMAL(18,0) NOT NULL,
    [EMAIL_REPRESENTANTE_DEMANDA] VARCHAR(100) NOT NULL CONSTRAINT [DF__TBL_ESTAB__EMAIL__34E8D562] DEFAULT 'orfao@orfao',
    [TARGET_DEMANDA] BIT NOT NULL CONSTRAINT [DF_TBL_ESTABELECIMENTOS_TARGET] DEFAULT 0,
    [EMAIL_REPRESENTANTE_VENDA] VARCHAR(100) NOT NULL CONSTRAINT [DF__TBL_ESTAB__EMAIL__38B96646] DEFAULT 'orfao@orfao',
    [TARGET_VENDA] BIT NOT NULL CONSTRAINT [DF_TBL_ESTABELECIMENTOS_TARGET_DEMANDA1] DEFAULT 0,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_ESTAB__DATA___7F4BDEC0] DEFAULT [dbo].[Mydate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_ESTABELECIMENTOS_DATA_INCLUSAO1] DEFAULT [dbo].[Mydate](),
    CONSTRAINT [PK_TBL_ESTABELECIMENTOS] PRIMARY KEY CLUSTERED ([CNPJ]),
    CONSTRAINT [IX_TBL_ESTABELECIMENTOS] UNIQUE NONCLUSTERED ([CNPJ])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_ESTABELECIMENTOS_ESFERA] (
    [COD_ESFERA] DECIMAL(18,0) NOT NULL,
    [ESFERA] VARCHAR(50) NOT NULL,
    [GESTAO] VARCHAR(50) NOT NULL,
    [COD_TIPO_PESSOA] DECIMAL(18,0) NOT NULL,
    CONSTRAINT [PK_TBL_ESFERA_ADMINISTRATIVA] PRIMARY KEY CLUSTERED ([COD_ESFERA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_ESTABELECIMENTOS_GRUPOS] (
    [ID_GRUPO_ESTABELECIMENTO] DECIMAL(18,0) NOT NULL,
    [GRUPO_ESTABELECIMENTO] VARCHAR(100) NOT NULL,
    [EMAIL_REPRESENTANTE_ACESSO] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_ESTABELECIMENTOS_GRUPOS_EMAIL_REPRESENTANTE_DEMANDA] DEFAULT 'orfao@orfao',
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_ESTABELECIMENTOS_GRUPOS_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_ESTABELECIMENTOS_GRUPOS_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_ESTABELECIMENTOS_GRUPOS] PRIMARY KEY CLUSTERED ([ID_GRUPO_ESTABELECIMENTO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_ESTABELECIMENTOS_NATUREZA] (
    [COD_NATUREZA] DECIMAL(18,0) NOT NULL,
    [NATUREZA] NVARCHAR(200) NOT NULL,
    [COD_ESFERA] DECIMAL(18,0) NOT NULL,
    CONSTRAINT [PK_TBL_RF_NATUREZA_JURIDICA] PRIMARY KEY CLUSTERED ([COD_NATUREZA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_ESTABELECIMENTOS_TIPO_PESSOA] (
    [COD_TIPO_PESSOA] DECIMAL(18,0) NOT NULL,
    [TIPO_PESSOA] VARCHAR(50) NOT NULL,
    CONSTRAINT [PK_TBL_TIPO_PESSOA] PRIMARY KEY CLUSTERED ([COD_TIPO_PESSOA]),
    CONSTRAINT [IX_TBL_TIPO_PESSOA] UNIQUE NONCLUSTERED ([TIPO_PESSOA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_FV_REPRESENTANTES_ACESSO] (
    [EMAIL_REPRESENTANTE_ACESSO] VARCHAR(100) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_FV_RE__DATA___347EC10E] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK__TBL_FV_R__FAE019BF8AC9ED6F] PRIMARY KEY CLUSTERED ([EMAIL_REPRESENTANTE_ACESSO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_FV_REPRESENTANTES_DEMANDA] (
    [EMAIL_REPRESENTANTE_DEMANDA] VARCHAR(100) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_FV_RE__DATA___1446FBA6] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME CONSTRAINT [DF__TBL_FV_RE__DATA___7DA38D70] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK__TBL_USUA__161CF72592E76942] PRIMARY KEY CLUSTERED ([EMAIL_REPRESENTANTE_DEMANDA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_FV_REPRESENTANTES_VENDA] (
    [EMAIL_REPRESENTANTE_VENDA] VARCHAR(100) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_FV_RE__DATA___6A1BB7B0] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK__TBL_FV_R__C691E58CF73BF71E] PRIMARY KEY CLUSTERED ([EMAIL_REPRESENTANTE_VENDA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA] (
    [ID] DECIMAL(18,0) NOT NULL,
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [EMAIL_REPRESENTANTE_DEMANDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_COTAS_DEMANDA_EMAIL_REPRESENTANTE_DEMANDA] DEFAULT 'orfao@orfao',
    [COD_PRODUTO_LINHA] DECIMAL(18,0) NOT NULL,
    [QTD_EQ] DECIMAL(18,2) NOT NULL CONSTRAINT [DF__TBL_COTAS__QTD__05E3CDB6] DEFAULT 0,
    [GARANTIDO] BIT NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_COTAS_DEMANDA_GARANTIDO] DEFAULT 0,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_COTAS_DEMANDA_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_MOVIMENTO_COTAS_DEMANDA] PRIMARY KEY CLUSTERED ([ANO],[MES],[EMAIL_REPRESENTANTE_DEMANDA],[COD_PRODUTO_LINHA]),
    CONSTRAINT [IX_TBL_MOVIMENTO_COTAS_DEMANDA] UNIQUE NONCLUSTERED ([ID])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA_BRASIL] (
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [COD_PRODUTO_LINHA] DECIMAL(18,0) NOT NULL,
    [QTD_EQ] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_MOVIM__QTD_U__133DC8D4] DEFAULT 0,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_MOVIM__DATA___1431ED0D] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_MOVIMENTO_COTAS_DEMANDA_BRASIL] PRIMARY KEY CLUSTERED ([ANO],[MES],[COD_PRODUTO_LINHA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_MOVIMENTO_COTAS_VENDA] (
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [EMAIL_REPRESENTANTE_VENDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_COTAS_VENDA_EMAIL_REPRESENTANTE_VENDA] DEFAULT 'orfao@orfao',
    [COD_PRODUTO] VARCHAR(50) NOT NULL,
    [QTD_UN] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_COTAS_c__QTD__0B9CA70C] DEFAULT 0,
    [QTD_BRL] DECIMAL(18,2) NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_COTAS_VENDA_QTD_UN1] DEFAULT 0,
    [GARANTIDO] BIT NOT NULL CONSTRAINT [DF__TBL_COTAS__IV_GA__0AA882D3] DEFAULT 0,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_COTAS_VENDA_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_COTAS_VENDA_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_MOVIMENTO_COTAS_VENDA] PRIMARY KEY CLUSTERED ([ANO],[MES],[EMAIL_REPRESENTANTE_VENDA],[COD_PRODUTO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_MOVIMENTO_COTAS_VENDA_BRASIL] (
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [COD_PRODUTO] VARCHAR(50) NOT NULL,
    [QTD_UN] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_MOVIM__QTD_U__218BE82B] DEFAULT 0,
    [ASP] DECIMAL(18,2) NOT NULL,
    [QTD_BRL] DECIMAL(18,2) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_MOVIM__DATA___22800C64] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK__TBL_MOVI__2643ACB379808C54] PRIMARY KEY CLUSTERED ([ANO],[MES],[COD_PRODUTO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_MOVIMENTO_DEMANDA] (
    [ID_REGISTRO] DECIMAL(10,0) NOT NULL,
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [CNPJ_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL,
    [CNPJ_ESTABELECIMENTO] DECIMAL(18,0) NOT NULL,
    [COD_PRODUTO] VARCHAR(50) NOT NULL,
    [QTD_UN] DECIMAL(18,0) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_MOVIM__DATA___675F4696] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK__TBL_MOVI__C7B81E6854242E42] PRIMARY KEY CLUSTERED ([ID_REGISTRO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_MOVIMENTO_ESTOQUE] (
    [ID_REGISTRO] DECIMAL(18,0) NOT NULL,
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [DIA] DECIMAL(18,0) NOT NULL,
    [COD_PRODUTO] VARCHAR(50) NOT NULL,
    [CNPJ_DISTRIBUIDOR] DECIMAL(18,0) NOT NULL,
    [QTD_UN] DECIMAL(18,0) NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_ESTOQUE_QTD_UN] DEFAULT 0,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_MOVIMENTO_ESTOQUE_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_MOVIMENTO_ESTOQUE] PRIMARY KEY CLUSTERED ([ANO],[MES],[DIA],[COD_PRODUTO],[CNPJ_DISTRIBUIDOR]),
    CONSTRAINT [IX_TBL_MOVIMENTO_ESTOQUE] UNIQUE NONCLUSTERED ([ID_REGISTRO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_MOVIMENTO_VENDA] (
    [ID_REGISTRO] DECIMAL(18,0) NOT NULL,
    [ANO] DECIMAL(18,0) NOT NULL,
    [MES] DECIMAL(18,0) NOT NULL,
    [CNPJ] DECIMAL(18,0) NOT NULL,
    [COD_PRODUTO] VARCHAR(50) NOT NULL,
    [QTD_UN] DECIMAL(18,0) NOT NULL CONSTRAINT [DF__TBL_MOVIM__QTD_N__5540965B] DEFAULT 0,
    [QTD_BRL] DECIMAL(18,2) NOT NULL CONSTRAINT [DF__TBL_MOVIM__VALOR__5728DECD] DEFAULT 0,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_MOVIM__DATA___6E0C4425] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_MOVIMENTO_VENDA] PRIMARY KEY CLUSTERED ([ID_REGISTRO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_MUNICIPIOS] (
    [COD_MUNICIPIO] VARCHAR(7) NOT NULL,
    [CIDADE] VARCHAR(200) NOT NULL,
    [CIDADE_UF] VARCHAR(200),
    [UF] VARCHAR(2) NOT NULL,
    [ESTADO] VARCHAR(100) NOT NULL,
    [CAPITAL] BIT NOT NULL CONSTRAINT [DF_TBL_MUNICIPIOS_CAPITAL] DEFAULT 0,
    [MICRO_REGIAO] VARCHAR(100) NOT NULL,
    [MESO_REGIAO] VARCHAR(100) NOT NULL,
    [REGIAO] VARCHAR(100) NOT NULL,
    [PAIS] VARCHAR(100) NOT NULL CONSTRAINT [DF__TBL_MUNICI__PAIS__39E294A9] DEFAULT 'BRASIL',
    [LATITUDE] FLOAT(53),
    [LONGITUDE] FLOAT(53),
    [EMAIL_REPRESENTANTE_DEMANDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_MUNICIPIOS_EMAIL_REPRESENTANTE_DEMANDA] DEFAULT 'orfao@orfao',
    [EMAIL_REPRESENTANTE_VENDA] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_MUNICIPIOS_EMAIL_REPRESENTANTE_DEMANDA1] DEFAULT 'orfao@orfao',
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_MUNICIPIOS_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_MUNICIPIOS_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_MUNICIPIOS] PRIMARY KEY CLUSTERED ([COD_MUNICIPIO]),
    CONSTRAINT [IX_TBL_MUNICIPIOS_CIDADE_UF] UNIQUE NONCLUSTERED ([CIDADE_UF])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_PRODUTOS] (
    [COD_PRODUTO] VARCHAR(50) NOT NULL,
    [PRODUTO] VARCHAR(100) NOT NULL,
    [COD_PRODUTO_LINHA] DECIMAL(18,0) NOT NULL,
    [COD_UNIDADE_VENDA] DECIMAL(18,0) NOT NULL,
    [QTD_UNIDADES_EMBALAGEM_VENDA] DECIMAL(18,0) NOT NULL,
    [COD_EMBALAGEM_VENDA] DECIMAL(18,0) NOT NULL,
    [FATOR_CONVERSAO_UNIDADE_EQUIVALENTE] DECIMAL(18,4) NOT NULL CONSTRAINT [DF__TBL_PRODU__FATOR__1A54DAB7] DEFAULT 1,
    [PRECO_BASE_UNIDADE_VENDA_BRL] DECIMAL(18,2) NOT NULL CONSTRAINT [DF__TBL_PRODU__PRECO__1B48FEF0] DEFAULT 1,
    [PRECO_BASE_UNIDADE_VENDA_USD] DECIMAL(18,2) NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_PRECO_BASE_DOLAR] DEFAULT 0,
    [ATIVO] BIT NOT NULL CONSTRAINT [DF__TBL_PRODU__ATIVO__1C3D2329] DEFAULT 1,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_PRODUTOS] PRIMARY KEY CLUSTERED ([COD_PRODUTO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_PRODUTOS_EMBALAGEM] (
    [COD_EMBALAGEM] DECIMAL(18,0) NOT NULL,
    [EMBALAGEM] VARCHAR(100) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_EMBALAGEM_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_EMBALAGEM_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_PRODUTOS_EMBALAGEM] PRIMARY KEY CLUSTERED ([COD_EMBALAGEM]),
    CONSTRAINT [IX_TBL_PRODUTOS_EMBALAGEM] UNIQUE NONCLUSTERED ([EMBALAGEM])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_PRODUTOS_GRUPOS] (
    [COD_PRODUTO_GRUPO] DECIMAL(18,0) NOT NULL,
    [PRODUTO_GRUPO] VARCHAR(100) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_GRUPOS_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_GRUPOS_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_PRODUTOS_GRUPOS] PRIMARY KEY CLUSTERED ([COD_PRODUTO_GRUPO]),
    CONSTRAINT [IX_TBL_PRODUTIVIDADE_GRUPO_PRODUTO_1] UNIQUE NONCLUSTERED ([PRODUTO_GRUPO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_PRODUTOS_GRUPOS_VENDA] (
    [COD_GRUPO_VENDA] DECIMAL(18,0) NOT NULL,
    [GRUPO_VENDA] VARCHAR(100) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_PRODU__DATA___2CFD9AD7] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_PRODU__DATA___2DF1BF10] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK__TBL_PRODUTOS_GRUPOS_VENDA] PRIMARY KEY CLUSTERED ([COD_GRUPO_VENDA]),
    CONSTRAINT [IX_TBL_PRODUTOS_GRUPOS_VENDA] UNIQUE NONCLUSTERED ([GRUPO_VENDA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_PRODUTOS_LINHAS] (
    [COD_PRODUTO_LINHA] DECIMAL(18,0) NOT NULL,
    [COD_PRODUTO_LINHA_ANTIGO] DECIMAL(18,0) NOT NULL,
    [PRODUTO_LINHA] VARCHAR(100) NOT NULL,
    [COD_UNIDADE_EQUIVALENTE] DECIMAL(18,0) NOT NULL,
    [COD_PRODUTO_GRUPO] DECIMAL(18,0) NOT NULL,
    [COD_GRUPO_VENDA] DECIMAL(18,0) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_LINHAS_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_LINHAS_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_PRODUTOS_LINHAS] PRIMARY KEY CLUSTERED ([COD_PRODUTO_LINHA]),
    CONSTRAINT [IX_TBL_PRODUTOS_LINHAS] UNIQUE NONCLUSTERED ([PRODUTO_LINHA])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_PRODUTOS_UNIDADES] (
    [COD_UNIDADE] DECIMAL(18,0) NOT NULL,
    [UNIDADE] VARCHAR(100) NOT NULL,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_UNIDADES_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_PRODUTOS_UNIDADES_DATA_ATUALIZACAO] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_PRODUTOS_UNIDADES] PRIMARY KEY CLUSTERED ([COD_UNIDADE]),
    CONSTRAINT [IX_TBL_PRODUTOS_UNIDADES] UNIQUE NONCLUSTERED ([UNIDADE])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_USUARIOS] (
    [EMAIL] VARCHAR(100) NOT NULL CONSTRAINT [DF__TBL_USUAR__EMAIL__2CBDA3B5] DEFAULT '@',
    [NOME] VARCHAR(200) NOT NULL CONSTRAINT [DF__TBL_USUARI__NOME__2DB1C7EE] DEFAULT '@',
    [NOME_CURTO] VARCHAR(50) NOT NULL,
    [COD_PERFIL] DECIMAL(18,0) NOT NULL,
    [ATIVO] BIT NOT NULL CONSTRAINT [DF__TBL_USUAR__ATIVO__373B3228] DEFAULT 1,
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_USUARIOS_DATA_INCLUSAO] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_USUARIOS_DATA_INCLUSAO1] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK_TBL_USUARIOS] PRIMARY KEY CLUSTERED ([EMAIL]),
    CONSTRAINT [IX_TBL_USUARIOS_NOME] UNIQUE NONCLUSTERED ([NOME]),
    CONSTRAINT [IX_TBL_USUARIOS_NOME_CURTO] UNIQUE NONCLUSTERED ([NOME_CURTO])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_USUARIOS_HIERARQUIA] (
    [EMAIL] VARCHAR(100) NOT NULL CONSTRAINT [DF__TBL_USUAR__EMAIL__605D434C] DEFAULT '@',
    [EMAIL_GERENTE] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_USUARIOS_HIERARQUIA_EMAIL1] DEFAULT 'gerente@orfao',
    [EMAIL_DIRETOR] VARCHAR(100) NOT NULL CONSTRAINT [DF_TBL_USUARIOS_HIERARQUIA_EMAIL_GERENTE1] DEFAULT 'diretor@orfao',
    [DATA_INCLUSAO] DATETIME NOT NULL CONSTRAINT [DF__TBL_USUAR__DATA___6339AFF7] DEFAULT [dbo].[MyDate](),
    [DATA_ATUALIZACAO] DATETIME NOT NULL CONSTRAINT [DF_TBL_USUARIOS_HIERARQUIA_DATA_INCLUSAO1] DEFAULT [dbo].[MyDate](),
    CONSTRAINT [PK__TBL_USUA__161CF725CC07CBA7] PRIMARY KEY CLUSTERED ([EMAIL])
);

-- CreateTable
CREATE TABLE [dbo].[TBL_USUARIOS_PERFIS] (
    [COD_PERFIL] DECIMAL(18,0) NOT NULL,
    [PERFIL] VARCHAR(100) NOT NULL,
    CONSTRAINT [PK_TBL_USUARIOS_PERFIS] PRIMARY KEY CLUSTERED ([COD_PERFIL])
);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_ano_mes_ativo_ANO] ON [dbo].[idx_ano_mes_ativo]([ANO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_ano_mes_ativo_ANO_MES] ON [dbo].[idx_ano_mes_ativo]([ANO_MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_ano_mes_ativo_DOLAR] ON [dbo].[idx_ano_mes_ativo]([DOLAR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_ano_mes_ativo_MES] ON [dbo].[idx_ano_mes_ativo]([MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_CNPJ_FORMATADO] ON [dbo].[idx_cnpj_ativo]([CNPJ_FORMATADO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_CNPJ_RAIZ] ON [dbo].[idx_cnpj_ativo]([CNPJ_RAIZ]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_CNPJ_VALIDO] ON [dbo].[idx_cnpj_ativo]([CNPJ_VALIDO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demanda_CNPJ_FORMATADO] ON [dbo].[idx_cnpj_ativo_demanda]([CNPJ_FORMATADO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demanda_CNPJ_RAIZ] ON [dbo].[idx_cnpj_ativo_demanda]([CNPJ_RAIZ]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demanda_CNPJ_VALIDO] ON [dbo].[idx_cnpj_ativo_demanda]([CNPJ_VALIDO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demanda_EMAIL_REPRESENTANTE_ACESSO] ON [dbo].[idx_cnpj_ativo_demanda]([EMAIL_REPRESENTANTE_ACESSO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demanda_EMAIL_REPRESENTANTE_DEMANDA] ON [dbo].[idx_cnpj_ativo_demanda]([EMAIL_REPRESENTANTE_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demanda_EMAIL_REPRESENTANTE_VENDA] ON [dbo].[idx_cnpj_ativo_demanda]([EMAIL_REPRESENTANTE_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demanda_SETORIZACAO_DEMANDA] ON [dbo].[idx_cnpj_ativo_demanda]([SETORIZACAO_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demandao_SETORIZACAO_ACESSO] ON [dbo].[idx_cnpj_ativo_demanda]([SETORIZACAO_ACESSO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_demandao_SETORIZACAO_VENDA] ON [dbo].[idx_cnpj_ativo_demanda]([SETORIZACAO_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_distribuidor_ativo] ON [dbo].[idx_cnpj_ativo_distribuidor]([CNPJ_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_distribuidor_ativo_ID_GRUPO_DISTRIBUIDOR] ON [dbo].[idx_cnpj_ativo_distribuidor]([ID_GRUPO_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_CNPJ_FORMATADO] ON [dbo].[idx_cnpj_ativo_setorizado]([CNPJ_FORMATADO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_CNPJ_RAIZ] ON [dbo].[idx_cnpj_ativo_setorizado]([CNPJ_RAIZ]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_CNPJ_VALIDO] ON [dbo].[idx_cnpj_ativo_setorizado]([CNPJ_VALIDO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_EMAIL_REPRESENTANTE_ACESSO] ON [dbo].[idx_cnpj_ativo_setorizado]([EMAIL_REPRESENTANTE_ACESSO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_EMAIL_REPRESENTANTE_DEMANDA] ON [dbo].[idx_cnpj_ativo_setorizado]([EMAIL_REPRESENTANTE_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_EMAIL_REPRESENTANTE_VENDA] ON [dbo].[idx_cnpj_ativo_setorizado]([EMAIL_REPRESENTANTE_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_SETORIZACAO_ACESSO] ON [dbo].[idx_cnpj_ativo_setorizado]([SETORIZACAO_ACESSO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_SETORIZACAO_DEMANDA] ON [dbo].[idx_cnpj_ativo_setorizado]([SETORIZACAO_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cnpj_ativo_setorizado_SETORIZACAO_VENDA] ON [dbo].[idx_cnpj_ativo_setorizado]([SETORIZACAO_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cod_municipio_ativo] ON [dbo].[idx_cod_municipio_ativo]([COD_MUNICIPIO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cod_produto_ativo_COD_PRODUTO_LINHA] ON [dbo].[idx_cod_produto_ativo]([COD_PRODUTO_LINHA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cod_produtos] ON [dbo].[idx_cod_produto_ativo]([COD_PRODUTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_cod_produto_linha] ON [dbo].[idx_cod_produto_linha_ativo]([COD_PRODUTO_LINHA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_email_representante_ativo] ON [dbo].[idx_email_representante_ativo]([EMAIL_REPRESENTANTE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_id_grupo_distribuidor_ativo] ON [dbo].[idx_id_grupo_distribuidor_ativo]([ID_GRUPO_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_setorizacao_EMAIL_REPRESENTANTE_ACESSO] ON [dbo].[idx_setorizacao]([EMAIL_REPRESENTANTE_ACESSO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_setorizacao_EMAIL_REPRESENTANTE_DEMANDA] ON [dbo].[idx_setorizacao]([EMAIL_REPRESENTANTE_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_setorizacao_EMAIL_REPRESENTANTE_VE] ON [dbo].[idx_setorizacao]([EMAIL_REPRESENTANTE_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_setorizacao_SETORIZACAO_ACESSO] ON [dbo].[idx_setorizacao]([SETORIZACAO_ACESSO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_setorizacao_SETORIZACAO_DEMANDA] ON [dbo].[idx_setorizacao]([SETORIZACAO_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_idx_setorizacao_SETORIZACAO_VENDA] ON [dbo].[idx_setorizacao]([SETORIZACAO_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SYS_DOLAR_PADRAO] ON [dbo].[SYS_DOLAR_PADRAO]([DOLAR_PADRAO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SYS_FABRICANTE_CNPJ_FABRICANTE] ON [dbo].[SYS_FABRICANTE]([CNPJ_FABRICANTE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SYS_FABRICANTE_ID_GRUPO_DISTRIBUIDOR] ON [dbo].[SYS_FABRICANTE]([ID_GRUPO_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_AGRUPAMENTO_COD_AGRUPAMENTO] ON [dbo].[SYS_MOVIMENTO_AGRUPAMENTO]([COD_AGRUPAMENTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SYS_MOVIMENTO_AGRUPAMENTO_AGRUPAMENTO] ON [dbo].[SYS_MOVIMENTO_AGRUPAMENTO]([AGRUPAMENTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SYS_MOVIMENTO_FORMA_COD_FORMA] ON [dbo].[SYS_MOVIMENTO_FORMA]([COD_FORMA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SYS_MOVIMENTO_FORMA_FORMA] ON [dbo].[SYS_MOVIMENTO_FORMA]([FORMA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_GRUPO_COD_GRUPO] ON [dbo].[SYS_MOVIMENTO_GRUPO]([COD_GRUPO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_GRUPO_GRUPO] ON [dbo].[SYS_MOVIMENTO_GRUPO]([GRUPO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_TIPO_COD_AGRUPAMENTO] ON [dbo].[SYS_MOVIMENTO_TIPO]([COD_AGRUPAMENTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_TIPO_COD_FORMA] ON [dbo].[SYS_MOVIMENTO_TIPO]([COD_FORMA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_TIPO_COD_GRUPO] ON [dbo].[SYS_MOVIMENTO_TIPO]([COD_GRUPO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_TIPO_COD_TIPO] ON [dbo].[SYS_MOVIMENTO_TIPO]([COD_TIPO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_TIPO_COD_VALOR] ON [dbo].[SYS_MOVIMENTO_TIPO]([COD_VALOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_TIPO_TIPO] ON [dbo].[SYS_MOVIMENTO_TIPO]([TIPO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_VALOR_COD_VALOR] ON [dbo].[SYS_MOVIMENTO_VALOR]([COD_VALOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_SYS_MOVIMENTO_VALOR_VALOR] ON [dbo].[SYS_MOVIMENTO_VALOR]([VALOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_SYS_USUARIOS_PADRAO] ON [dbo].[SYS_USUARIOS_PADRAO]([EMAIL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_ANOS] ON [dbo].[TBL_DATAS_ANOS]([ANO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_DIAS] ON [dbo].[TBL_DATAS_DIAS]([DIA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_DOLAR_ANO] ON [dbo].[TBL_DATAS_DOLAR]([ANO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_DOLAR_DOLAR] ON [dbo].[TBL_DATAS_DOLAR]([DOLAR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_DOLAR_MES] ON [dbo].[TBL_DATAS_DOLAR]([MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_MES] ON [dbo].[TBL_DATAS_MESES]([MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_MES_FISCAL] ON [dbo].[TBL_DATAS_MESES]([MES_FISCAL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_MES_FISCAL_SIGLA] ON [dbo].[TBL_DATAS_MESES]([MES_FISCAL_SIGLA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_MES_SIGLA] ON [dbo].[TBL_DATAS_MESES]([MES_SIGLA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_SEMESTRE] ON [dbo].[TBL_DATAS_MESES]([SEMESTRE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_SEMESTRE_FISCAL] ON [dbo].[TBL_DATAS_MESES]([SEMESTRE_FISCAL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_SEMESTRE_SIGLA] ON [dbo].[TBL_DATAS_MESES]([SEMESTRE_SIGLA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_SEMESTREFISCAL_SIGLA] ON [dbo].[TBL_DATAS_MESES]([SEMESTRE_FISCAL_SIGLA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_TRIMESTRE] ON [dbo].[TBL_DATAS_MESES]([TRIMESTRE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_TRIMESTRE_FISCAL] ON [dbo].[TBL_DATAS_MESES]([TRIMESTRE_FISCAL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_TRIMESTRE_FISCAL_SIGLA] ON [dbo].[TBL_DATAS_MESES]([TRIMESTRE_FISCAL_SIGLA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_MESES_TRIMESTRE_SIGLA] ON [dbo].[TBL_DATAS_MESES]([TRIMESTRE_SIGLA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_TBL_DATAS_PERIODOS_PERIODO_INDICE] ON [dbo].[TBL_DATAS_PERIODOS]([PERIODO_INDICE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DATAS_PERIODOS_PERIODO] ON [dbo].[TBL_DATAS_PERIODOS]([PERIODO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES] ON [dbo].[TBL_DISTRIBUIDORES]([CNPJ_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES_1] ON [dbo].[TBL_DISTRIBUIDORES]([CNPJ_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES_CNPJ_DISTRIBUIDOR] ON [dbo].[TBL_DISTRIBUIDORES]([CNPJ_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES_ESTABELECIMENTO] ON [dbo].[TBL_DISTRIBUIDORES]([ESTABELECIMENTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES_ID_GRUPO_DISTRIBUIDOR] ON [dbo].[TBL_DISTRIBUIDORES]([ID_GRUPO_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES_NOME_FANTASIA] ON [dbo].[TBL_DISTRIBUIDORES]([NOME_FANTASIA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES_RAZAO_SOCIAL] ON [dbo].[TBL_DISTRIBUIDORES]([RAZAO_SOCIAL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_TBL_DISTRIBUIDORES_GRUPOS] ON [dbo].[TBL_DISTRIBUIDORES_GRUPOS]([ID_GRUPO_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_TBL_DISTRIBUIDORES_GRUPOS_EMAIL_REPRESENTANTE_DEMANDA] ON [dbo].[TBL_DISTRIBUIDORES_GRUPOS]([EMAIL_REPRESENTANTE_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_TBL_DISTRIBUIDORES_GRUPOS_GRUPO_DISTRIBUIDOR] ON [dbo].[TBL_DISTRIBUIDORES_GRUPOS]([GRUPO_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDXX_TBL_DISTRIBUIDORES_GRUPOS_EMAIL_REPRESENTANTE_VENDA] ON [dbo].[TBL_DISTRIBUIDORES_GRUPOS]([EMAIL_REPRESENTANTE_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES_TIPO_1] ON [dbo].[TBL_DISTRIBUIDORES_TIPO]([COD_TIPO_DISTRIBUDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_DISTRIBUIDORES_TIPO_2] ON [dbo].[TBL_DISTRIBUIDORES_TIPO]([TIPO_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_CEP] ON [dbo].[TBL_ESTABELECIMENTOS]([CEP]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_CNES] ON [dbo].[TBL_ESTABELECIMENTOS]([CNES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_COD_MUNICIPIO] ON [dbo].[TBL_ESTABELECIMENTOS]([COD_MUNICIPIO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_COD_NATUREZA] ON [dbo].[TBL_ESTABELECIMENTOS]([COD_NATUREZA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_EMAIL_REPRESENTANTE_DEMANDA] ON [dbo].[TBL_ESTABELECIMENTOS]([EMAIL_REPRESENTANTE_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_EMAIL_REPRESENTANTE_VENDA] ON [dbo].[TBL_ESTABELECIMENTOS]([EMAIL_REPRESENTANTE_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_NOME_FANTASIA] ON [dbo].[TBL_ESTABELECIMENTOS]([NOME_FANTASIA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_RAZAO_SOCIAL] ON [dbo].[TBL_ESTABELECIMENTOS]([RAZAO_SOCIAL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_TARGET_DEMANDA] ON [dbo].[TBL_ESTABELECIMENTOS]([TARGET_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_TARGET_VENDA] ON [dbo].[TBL_ESTABELECIMENTOS]([TARGET_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_ESFERA] ON [dbo].[TBL_ESTABELECIMENTOS_ESFERA]([COD_ESFERA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_ESFERA_COD_TIPO_PESSOA] ON [dbo].[TBL_ESTABELECIMENTOS_ESFERA]([COD_TIPO_PESSOA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_ESFERA_ESFERA] ON [dbo].[TBL_ESTABELECIMENTOS_ESFERA]([ESFERA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_ESFERA_GESTAO] ON [dbo].[TBL_ESTABELECIMENTOS_ESFERA]([GESTAO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_GRUPOS] ON [dbo].[TBL_ESTABELECIMENTOS_GRUPOS]([ID_GRUPO_ESTABELECIMENTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_GRUPOS_EMAIL_REPRESENTANTE_ACESSO] ON [dbo].[TBL_ESTABELECIMENTOS_GRUPOS]([EMAIL_REPRESENTANTE_ACESSO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_ESTABELECIMENTOS_GRUPOS_GRUPO_ESTABELECIMENTO] ON [dbo].[TBL_ESTABELECIMENTOS_GRUPOS]([GRUPO_ESTABELECIMENTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_FV_REPRESENTANTES_ACESSO] ON [dbo].[TBL_FV_REPRESENTANTES_ACESSO]([EMAIL_REPRESENTANTE_ACESSO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_FV_REPRESENTANTES_DEMANDA] ON [dbo].[TBL_FV_REPRESENTANTES_DEMANDA]([EMAIL_REPRESENTANTE_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_FV_REPRESENTANTES_VENDA] ON [dbo].[TBL_FV_REPRESENTANTES_VENDA]([EMAIL_REPRESENTANTE_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_COTAS_DEMANDA_ANO] ON [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA]([ANO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_COTAS_DEMANDA_COD_PRODUTO_LINHA] ON [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA]([COD_PRODUTO_LINHA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_COTAS_DEMANDA_EMAIL_REPRESENTANTE_DEMANDA] ON [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA]([EMAIL_REPRESENTANTE_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_COTAS_DEMANDA_MES] ON [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA]([MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_COTAS_VENDA] ON [dbo].[TBL_MOVIMENTO_COTAS_VENDA]([MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_COTAS_VENDA_ANO] ON [dbo].[TBL_MOVIMENTO_COTAS_VENDA]([ANO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_COTAS_VENDA_COD_PRODUTO] ON [dbo].[TBL_MOVIMENTO_COTAS_VENDA]([COD_PRODUTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_COTAS_VENDA_EMAIL_REPRESENTANTE_VENDA] ON [dbo].[TBL_MOVIMENTO_COTAS_VENDA]([EMAIL_REPRESENTANTE_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_DEMANDA_ANO] ON [dbo].[TBL_MOVIMENTO_DEMANDA]([ANO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_DEMANDA_CNPJ_DISTRIBUIDOR] ON [dbo].[TBL_MOVIMENTO_DEMANDA]([CNPJ_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_DEMANDA_COD_PRODUTO] ON [dbo].[TBL_MOVIMENTO_DEMANDA]([COD_PRODUTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_DEMANDA_CPNJ_ESTABELECIMENTO] ON [dbo].[TBL_MOVIMENTO_DEMANDA]([CNPJ_ESTABELECIMENTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_DEMANDA_MES] ON [dbo].[TBL_MOVIMENTO_DEMANDA]([MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_ESTOQUE_ANO] ON [dbo].[TBL_MOVIMENTO_ESTOQUE]([ANO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_ESTOQUE_CNPJ_DISTRIBUIDOR] ON [dbo].[TBL_MOVIMENTO_ESTOQUE]([CNPJ_DISTRIBUIDOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_ESTOQUE_COD_PRODUTO] ON [dbo].[TBL_MOVIMENTO_ESTOQUE]([COD_PRODUTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_ESTOQUE_MES] ON [dbo].[TBL_MOVIMENTO_ESTOQUE]([MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_VENDA_ANO] ON [dbo].[TBL_MOVIMENTO_VENDA]([ANO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_VENDA_CNPJ] ON [dbo].[TBL_MOVIMENTO_VENDA]([CNPJ]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_VENDA_COD_PRODUTO] ON [dbo].[TBL_MOVIMENTO_VENDA]([COD_PRODUTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_MOVIMENTO_VENDA_MES] ON [dbo].[TBL_MOVIMENTO_VENDA]([MES]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_TBL_MUNICIPIOS_CIDADE_UF] ON [dbo].[TBL_MUNICIPIOS]([CIDADE_UF]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_TBL_MUNICIPIOS_EMAIL_REPRESENTANTE_DEMANDA] ON [dbo].[TBL_MUNICIPIOS]([EMAIL_REPRESENTANTE_DEMANDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IDX_TBL_MUNICIPIOS_EMAIL_REPRESENTANTE_VENDA] ON [dbo].[TBL_MUNICIPIOS]([EMAIL_REPRESENTANTE_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_PRODUTO_COD_LINHA] ON [dbo].[TBL_PRODUTOS]([COD_PRODUTO_LINHA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_PRODUTO_PRODUTO] ON [dbo].[TBL_PRODUTOS]([PRODUTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_PRODUTOS_EMBALAGEM_COD_EMBALAGE] ON [dbo].[TBL_PRODUTOS_EMBALAGEM]([COD_EMBALAGEM]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_PRODUTOS_GRUPOS] ON [dbo].[TBL_PRODUTOS_GRUPOS]([COD_PRODUTO_GRUPO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_PRODUTOS_GRUPOS_VENDA_1] ON [dbo].[TBL_PRODUTOS_GRUPOS_VENDA]([COD_GRUPO_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_PRODUTOS_GRUPOS_VENDA_2] ON [dbo].[TBL_PRODUTOS_GRUPOS_VENDA]([GRUPO_VENDA]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_PRODUTOS_UNIDADES_COD_UNIDADE] ON [dbo].[TBL_PRODUTOS_UNIDADES]([COD_UNIDADE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_ATIVO_IDX] ON [dbo].[TBL_USUARIOS]([ATIVO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_COD_PERFIL] ON [dbo].[TBL_USUARIOS]([COD_PERFIL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_EMAIL] ON [dbo].[TBL_USUARIOS]([EMAIL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_NOME_CURTO_IDX] ON [dbo].[TBL_USUARIOS]([NOME_CURTO]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_NOME_IDX] ON [dbo].[TBL_USUARIOS]([NOME]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_HIERARQUIA_EMAIL] ON [dbo].[TBL_USUARIOS_HIERARQUIA]([EMAIL]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_HIERARQUIA_EMAIL_DIRETOR] ON [dbo].[TBL_USUARIOS_HIERARQUIA]([EMAIL_DIRETOR]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_HIERARQUIA_EMAIL_GERENTE] ON [dbo].[TBL_USUARIOS_HIERARQUIA]([EMAIL_GERENTE]);

-- CreateIndex
CREATE NONCLUSTERED INDEX [IX_TBL_USUARIOS_PERFIS] ON [dbo].[TBL_USUARIOS_PERFIS]([COD_PERFIL]);

-- AddForeignKey
ALTER TABLE [dbo].[SYS_FABRICANTE] ADD CONSTRAINT [FK_SYS_FABRICANTE_TBL_DISTRIBUIDORES] FOREIGN KEY ([CNPJ_FABRICANTE]) REFERENCES [dbo].[TBL_DISTRIBUIDORES]([CNPJ_DISTRIBUIDOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_FABRICANTE] ADD CONSTRAINT [FK_TBL_FABRICANTE_TBL_DISTRIBUIDORES_GRUPOS] FOREIGN KEY ([ID_GRUPO_DISTRIBUIDOR]) REFERENCES [dbo].[TBL_DISTRIBUIDORES_GRUPOS]([ID_GRUPO_DISTRIBUIDOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_FABRICANTE] ADD CONSTRAINT [FK_TBL_FABRICANTE_TBL_ESTABELECIMENTOS] FOREIGN KEY ([CNPJ_FABRICANTE]) REFERENCES [dbo].[TBL_ESTABELECIMENTOS]([CNPJ]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_MOVIMENTO_TIPO] ADD CONSTRAINT [FK_SYS_MOVIMENTO_TIPO_SYS_MOVIMENTO_AGRUPAMENTO] FOREIGN KEY ([COD_AGRUPAMENTO]) REFERENCES [dbo].[SYS_MOVIMENTO_AGRUPAMENTO]([COD_AGRUPAMENTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_MOVIMENTO_TIPO] ADD CONSTRAINT [FK_SYS_MOVIMENTO_TIPO_SYS_MOVIMENTO_FORMA] FOREIGN KEY ([COD_FORMA]) REFERENCES [dbo].[SYS_MOVIMENTO_FORMA]([COD_FORMA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_MOVIMENTO_TIPO] ADD CONSTRAINT [FK_SYS_MOVIMENTO_TIPO_SYS_MOVIMENTO_GRUPO] FOREIGN KEY ([COD_GRUPO]) REFERENCES [dbo].[SYS_MOVIMENTO_GRUPO]([COD_GRUPO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_MOVIMENTO_TIPO] ADD CONSTRAINT [FK_SYS_MOVIMENTO_TIPO_SYS_MOVIMENTO_VALOR] FOREIGN KEY ([COD_VALOR]) REFERENCES [dbo].[SYS_MOVIMENTO_VALOR]([COD_VALOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_USUARIOS_PADRAO] ADD CONSTRAINT [FK_SYS_USUARIOS_PADRAO_TBL_FV_REPRESENTANTES_ACESSO] FOREIGN KEY ([EMAIL]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_ACESSO]([EMAIL_REPRESENTANTE_ACESSO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_USUARIOS_PADRAO] ADD CONSTRAINT [FK_SYS_USUARIOS_PADRAO_TBL_FV_REPRESENTANTES_DEMANDA] FOREIGN KEY ([EMAIL]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_DEMANDA]([EMAIL_REPRESENTANTE_DEMANDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_USUARIOS_PADRAO] ADD CONSTRAINT [FK_SYS_USUARIOS_PADRAO_TBL_FV_REPRESENTANTES_VENDA] FOREIGN KEY ([EMAIL]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_VENDA]([EMAIL_REPRESENTANTE_VENDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_USUARIOS_PADRAO] ADD CONSTRAINT [FK_SYS_USUARIOS_PADRAO_TBL_USUARIOS] FOREIGN KEY ([EMAIL]) REFERENCES [dbo].[TBL_USUARIOS]([EMAIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[SYS_USUARIOS_PADRAO] ADD CONSTRAINT [FK_SYS_USUARIOS_PADRAO_TBL_USUARIOS_HIERARQUIA] FOREIGN KEY ([EMAIL]) REFERENCES [dbo].[TBL_USUARIOS_HIERARQUIA]([EMAIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_DATAS_DOLAR] ADD CONSTRAINT [FK_TBL_DATAS_DOLAR_TBL_DATAS_ANOS] FOREIGN KEY ([ANO]) REFERENCES [dbo].[TBL_DATAS_ANOS]([ANO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_DATAS_DOLAR] ADD CONSTRAINT [FK_TBL_DATAS_DOLAR_TBL_DATAS_MESES] FOREIGN KEY ([MES]) REFERENCES [dbo].[TBL_DATAS_MESES]([MES]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_DISTRIBUIDORES] ADD CONSTRAINT [FK_TBL_DISTRIBUIDORES_TBL_DISTRIBUIDORES_GRUPOS] FOREIGN KEY ([ID_GRUPO_DISTRIBUIDOR]) REFERENCES [dbo].[TBL_DISTRIBUIDORES_GRUPOS]([ID_GRUPO_DISTRIBUIDOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_DISTRIBUIDORES] ADD CONSTRAINT [FK_TBL_DISTRIBUIDORES_TBL_ESTABELECIMENTOS] FOREIGN KEY ([CNPJ_DISTRIBUIDOR]) REFERENCES [dbo].[TBL_ESTABELECIMENTOS]([CNPJ]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_DISTRIBUIDORES_GRUPOS] ADD CONSTRAINT [FK_TBL_DISTRIBUIDORES_GRUPOS_TBL_DISTRIBUIDORES_TIPO] FOREIGN KEY ([COD_TIPO_DISTRIBUIDOR]) REFERENCES [dbo].[TBL_DISTRIBUIDORES_TIPO]([COD_TIPO_DISTRIBUDOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_DISTRIBUIDORES_GRUPOS] ADD CONSTRAINT [FK_TBL_DISTRIBUIDORES_GRUPOS_TBL_FV_REPRESENTANTES_DEMANDA] FOREIGN KEY ([EMAIL_REPRESENTANTE_DEMANDA]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_DEMANDA]([EMAIL_REPRESENTANTE_DEMANDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_DISTRIBUIDORES_GRUPOS] ADD CONSTRAINT [FK_TBL_DISTRIBUIDORES_GRUPOS_TBL_FV_REPRESENTANTES_VENDA] FOREIGN KEY ([EMAIL_REPRESENTANTE_VENDA]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_VENDA]([EMAIL_REPRESENTANTE_VENDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_ESTABELECIMENTOS] ADD CONSTRAINT [FK_TBL_ESTABELECIMENTOS_TBL_ESTABELECIMENTOS_GRUPOS] FOREIGN KEY ([ID_GRUPO_ESTABELECIMENTO]) REFERENCES [dbo].[TBL_ESTABELECIMENTOS_GRUPOS]([ID_GRUPO_ESTABELECIMENTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_ESTABELECIMENTOS] ADD CONSTRAINT [FK_TBL_ESTABELECIMENTOS_TBL_ESTABELECIMENTOS_NATUREZA] FOREIGN KEY ([COD_NATUREZA]) REFERENCES [dbo].[TBL_ESTABELECIMENTOS_NATUREZA]([COD_NATUREZA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_ESTABELECIMENTOS] ADD CONSTRAINT [FK_TBL_ESTABELECIMENTOS_TBL_FV_REPRESENTANTES] FOREIGN KEY ([EMAIL_REPRESENTANTE_DEMANDA]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_DEMANDA]([EMAIL_REPRESENTANTE_DEMANDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_ESTABELECIMENTOS] ADD CONSTRAINT [FK_TBL_ESTABELECIMENTOS_TBL_FV_REPRESENTANTES_VENDA] FOREIGN KEY ([EMAIL_REPRESENTANTE_VENDA]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_VENDA]([EMAIL_REPRESENTANTE_VENDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_ESTABELECIMENTOS] ADD CONSTRAINT [FK_TBL_ESTABELECIMENTOS_TBL_MUNICIPIOS] FOREIGN KEY ([COD_MUNICIPIO]) REFERENCES [dbo].[TBL_MUNICIPIOS]([COD_MUNICIPIO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_ESTABELECIMENTOS_ESFERA] ADD CONSTRAINT [FK_TBL_ESTABELECIMENTOS_ESFERA_TBL_ESTABELECIMENTOS_TIPO_PESSOA] FOREIGN KEY ([COD_TIPO_PESSOA]) REFERENCES [dbo].[TBL_ESTABELECIMENTOS_TIPO_PESSOA]([COD_TIPO_PESSOA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_ESTABELECIMENTOS_GRUPOS] ADD CONSTRAINT [FK_TBL_ESTABELECIMENTOS_GRUPOS_TBL_FV_REPRESENTANTES_ACESSO] FOREIGN KEY ([EMAIL_REPRESENTANTE_ACESSO]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_ACESSO]([EMAIL_REPRESENTANTE_ACESSO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_ESTABELECIMENTOS_NATUREZA] ADD CONSTRAINT [FK_TBL_ESTABELECIMENTOS_NATUREZA_TBL_ESTABELECIMENTOS_ESFERA] FOREIGN KEY ([COD_ESFERA]) REFERENCES [dbo].[TBL_ESTABELECIMENTOS_ESFERA]([COD_ESFERA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_FV_REPRESENTANTES_ACESSO] ADD CONSTRAINT [FK_TBL_FV_REPRESENTANTES_ACESSO_TBL_USUARIOS_HIERARQUIA] FOREIGN KEY ([EMAIL_REPRESENTANTE_ACESSO]) REFERENCES [dbo].[TBL_USUARIOS_HIERARQUIA]([EMAIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_FV_REPRESENTANTES_DEMANDA] ADD CONSTRAINT [FK_TBL_FV_REPRESENTANTES_DEMANDA_TBL_USUARIOS_HIERARQUIA] FOREIGN KEY ([EMAIL_REPRESENTANTE_DEMANDA]) REFERENCES [dbo].[TBL_USUARIOS_HIERARQUIA]([EMAIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_FV_REPRESENTANTES_VENDA] ADD CONSTRAINT [FK_TBL_FV_REPRESENTANTES_VENDA_TBL_USUARIOS_HIERARQUIA] FOREIGN KEY ([EMAIL_REPRESENTANTE_VENDA]) REFERENCES [dbo].[TBL_USUARIOS_HIERARQUIA]([EMAIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_COTAS_DEMANDA_TBL_FV_REPRESENTANTES_DEMANDA] FOREIGN KEY ([EMAIL_REPRESENTANTE_DEMANDA]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_DEMANDA]([EMAIL_REPRESENTANTE_DEMANDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_COTAS_DEMANDA_TBL_MOVIMENTO_COTAS_DEMANDA_BRASIL] FOREIGN KEY ([ANO], [MES], [COD_PRODUTO_LINHA]) REFERENCES [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA_BRASIL]([ANO],[MES],[COD_PRODUTO_LINHA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA_BRASIL] ADD CONSTRAINT [FK_TBL_MOVIMENTO_COTAS_DEMANDA_BRASIL_TBL_PRODUTOS_LINHAS] FOREIGN KEY ([COD_PRODUTO_LINHA]) REFERENCES [dbo].[TBL_PRODUTOS_LINHAS]([COD_PRODUTO_LINHA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA_BRASIL] ADD CONSTRAINT [FK_TBL_MOVIMENTO_COTAS_DEMANDA_UN_BRASIL_TBL_DATAS_ANOS] FOREIGN KEY ([ANO]) REFERENCES [dbo].[TBL_DATAS_ANOS]([ANO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_DEMANDA_BRASIL] ADD CONSTRAINT [FK_TBL_MOVIMENTO_COTAS_DEMANDA_UN_BRASIL_TBL_DATAS_MESES] FOREIGN KEY ([MES]) REFERENCES [dbo].[TBL_DATAS_MESES]([MES]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_VENDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_COTAS_VENDA_TBL_FV_REPRESENTANTES_VENDA] FOREIGN KEY ([EMAIL_REPRESENTANTE_VENDA]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_VENDA]([EMAIL_REPRESENTANTE_VENDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_VENDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_COTAS_VENDA_TBL_MOVIMENTO_COTAS_VENDA_BRASIL] FOREIGN KEY ([ANO], [MES], [COD_PRODUTO]) REFERENCES [dbo].[TBL_MOVIMENTO_COTAS_VENDA_BRASIL]([ANO],[MES],[COD_PRODUTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_VENDA_BRASIL] ADD CONSTRAINT [FK__TBL_MOVIM__COD_P__255C790F] FOREIGN KEY ([COD_PRODUTO]) REFERENCES [dbo].[TBL_PRODUTOS]([COD_PRODUTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_VENDA_BRASIL] ADD CONSTRAINT [FK__TBL_MOVIMEN__ANO__2374309D] FOREIGN KEY ([ANO]) REFERENCES [dbo].[TBL_DATAS_ANOS]([ANO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_COTAS_VENDA_BRASIL] ADD CONSTRAINT [FK__TBL_MOVIMEN__MES__246854D6] FOREIGN KEY ([MES]) REFERENCES [dbo].[TBL_DATAS_MESES]([MES]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_DEMANDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_DEMANDA_TBL_DATAS_ANOS] FOREIGN KEY ([ANO]) REFERENCES [dbo].[TBL_DATAS_ANOS]([ANO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_DEMANDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_DEMANDA_TBL_DATAS_MESES] FOREIGN KEY ([MES]) REFERENCES [dbo].[TBL_DATAS_MESES]([MES]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_DEMANDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_DEMANDA_TBL_DISTRIBUIDORES] FOREIGN KEY ([CNPJ_DISTRIBUIDOR]) REFERENCES [dbo].[TBL_DISTRIBUIDORES]([CNPJ_DISTRIBUIDOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_DEMANDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_DEMANDA_TBL_ESTABELECIMENTOS] FOREIGN KEY ([CNPJ_ESTABELECIMENTO]) REFERENCES [dbo].[TBL_ESTABELECIMENTOS]([CNPJ]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_DEMANDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_DEMANDA_TBL_PRODUTOS] FOREIGN KEY ([COD_PRODUTO]) REFERENCES [dbo].[TBL_PRODUTOS]([COD_PRODUTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_ESTOQUE] ADD CONSTRAINT [FK_TBL_MOVIMENTO_ESTOQUE_TBL_DATAS_ANOS] FOREIGN KEY ([ANO]) REFERENCES [dbo].[TBL_DATAS_ANOS]([ANO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_ESTOQUE] ADD CONSTRAINT [FK_TBL_MOVIMENTO_ESTOQUE_TBL_DATAS_DIAS] FOREIGN KEY ([DIA]) REFERENCES [dbo].[TBL_DATAS_DIAS]([DIA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_ESTOQUE] ADD CONSTRAINT [FK_TBL_MOVIMENTO_ESTOQUE_TBL_DATAS_MESES] FOREIGN KEY ([MES]) REFERENCES [dbo].[TBL_DATAS_MESES]([MES]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_ESTOQUE] ADD CONSTRAINT [FK_TBL_MOVIMENTO_ESTOQUE_TBL_DISTRIBUIDORES] FOREIGN KEY ([CNPJ_DISTRIBUIDOR]) REFERENCES [dbo].[TBL_DISTRIBUIDORES]([CNPJ_DISTRIBUIDOR]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_ESTOQUE] ADD CONSTRAINT [FK_TBL_MOVIMENTO_ESTOQUE_TBL_PRODUTOS] FOREIGN KEY ([COD_PRODUTO]) REFERENCES [dbo].[TBL_PRODUTOS]([COD_PRODUTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_VENDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_VENDA_TBL_DATAS_ANOS] FOREIGN KEY ([ANO]) REFERENCES [dbo].[TBL_DATAS_ANOS]([ANO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_VENDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_VENDA_TBL_DATAS_MESES] FOREIGN KEY ([MES]) REFERENCES [dbo].[TBL_DATAS_MESES]([MES]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_VENDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_VENDA_TBL_ESTABELECIMENTOS] FOREIGN KEY ([CNPJ]) REFERENCES [dbo].[TBL_ESTABELECIMENTOS]([CNPJ]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MOVIMENTO_VENDA] ADD CONSTRAINT [FK_TBL_MOVIMENTO_VENDA_TBL_PRODUTOS] FOREIGN KEY ([COD_PRODUTO]) REFERENCES [dbo].[TBL_PRODUTOS]([COD_PRODUTO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MUNICIPIOS] ADD CONSTRAINT [FK_TBL_MUNICIPIOS_TBL_FV_REPRESENTANTES_DEMANDA] FOREIGN KEY ([EMAIL_REPRESENTANTE_DEMANDA]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_DEMANDA]([EMAIL_REPRESENTANTE_DEMANDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_MUNICIPIOS] ADD CONSTRAINT [FK_TBL_MUNICIPIOS_TBL_FV_REPRESENTANTES_VENDA] FOREIGN KEY ([EMAIL_REPRESENTANTE_VENDA]) REFERENCES [dbo].[TBL_FV_REPRESENTANTES_VENDA]([EMAIL_REPRESENTANTE_VENDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_PRODUTOS] ADD CONSTRAINT [FK_TBL_PRODUTOS_TBL_PRODUTOS_EMBALAGEM] FOREIGN KEY ([COD_EMBALAGEM_VENDA]) REFERENCES [dbo].[TBL_PRODUTOS_EMBALAGEM]([COD_EMBALAGEM]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_PRODUTOS] ADD CONSTRAINT [FK_TBL_PRODUTOS_TBL_PRODUTOS_LINHAS] FOREIGN KEY ([COD_PRODUTO_LINHA]) REFERENCES [dbo].[TBL_PRODUTOS_LINHAS]([COD_PRODUTO_LINHA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_PRODUTOS] ADD CONSTRAINT [FK_TBL_PRODUTOS_TBL_PRODUTOS_UNIDADES] FOREIGN KEY ([COD_UNIDADE_VENDA]) REFERENCES [dbo].[TBL_PRODUTOS_UNIDADES]([COD_UNIDADE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_PRODUTOS_LINHAS] ADD CONSTRAINT [FK_TBL_PRODUTOS_LINHAS_TBL_PRODUTOS_GRUPOS] FOREIGN KEY ([COD_PRODUTO_GRUPO]) REFERENCES [dbo].[TBL_PRODUTOS_GRUPOS]([COD_PRODUTO_GRUPO]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_PRODUTOS_LINHAS] ADD CONSTRAINT [FK_TBL_PRODUTOS_LINHAS_TBL_PRODUTOS_GRUPOS_VENDA] FOREIGN KEY ([COD_GRUPO_VENDA]) REFERENCES [dbo].[TBL_PRODUTOS_GRUPOS_VENDA]([COD_GRUPO_VENDA]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_PRODUTOS_LINHAS] ADD CONSTRAINT [FK_TBL_PRODUTOS_LINHAS_TBL_PRODUTOS_UNIDADES] FOREIGN KEY ([COD_UNIDADE_EQUIVALENTE]) REFERENCES [dbo].[TBL_PRODUTOS_UNIDADES]([COD_UNIDADE]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_USUARIOS] ADD CONSTRAINT [FK_TBL_USUARIOS_TBL_USUARIOS_PERFIS] FOREIGN KEY ([COD_PERFIL]) REFERENCES [dbo].[TBL_USUARIOS_PERFIS]([COD_PERFIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_USUARIOS_HIERARQUIA] ADD CONSTRAINT [FK_TBL_USUARIOS_HIERARQUIA_TBL_USUARIOS] FOREIGN KEY ([EMAIL]) REFERENCES [dbo].[TBL_USUARIOS]([EMAIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_USUARIOS_HIERARQUIA] ADD CONSTRAINT [FK_TBL_USUARIOS_HIERARQUIA_TBL_USUARIOS1] FOREIGN KEY ([EMAIL_GERENTE]) REFERENCES [dbo].[TBL_USUARIOS]([EMAIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE [dbo].[TBL_USUARIOS_HIERARQUIA] ADD CONSTRAINT [FK_TBL_USUARIOS_HIERARQUIA_TBL_USUARIOS2] FOREIGN KEY ([EMAIL_DIRETOR]) REFERENCES [dbo].[TBL_USUARIOS]([EMAIL]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
