# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - csladminback

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://wfbimgdocker.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_fcc8a0c25da74c388893069c327f07dd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_fb5a92998e1047398ad9c5d47ab28410 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wfbimgdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fcc8a0c25da74c388893069c327f07dd }}/csladminback2:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'csladminback'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_133f63f25260438a8b79d63d2c4ed320 }}
        images: 'wfbimgdocker.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_fcc8a0c25da74c388893069c327f07dd }}/csladminback2:${{ github.sha }}'